In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
df = pd.read_csv("/content/Position_Salaries.csv")
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [ ]:
X =df.iloc[:,1:-1]
y=df.iloc[:,-1].values
print(X)
print(y)

   Level
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
y=y.reshape(-1,1)
#sc_X.fit(X)
#sc_y.fit(y)
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)
#print(X)
#print(y)
#y=y.reshape(-1)
#y
p1= sc_X.transform([[5000]])
print(p1)
p2=sc_X.inverse_transform(p1)
print(p2)

[[5000.]]
[[5000.]]


In [ ]:
from sklearn.model_selection import train_test_split
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)


[[-0.17407766]
 [ 1.5666989 ]
 [-1.21854359]
 [ 0.52223297]
 [ 0.87038828]
 [-0.52223297]
 [-1.5666989 ]
 [ 0.17407766]]
[[-0.87038828]
 [ 1.21854359]]


In [ ]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train,y_train)

SVR()

In [ ]:
y_pred =svr.predict(X_test)
print(y_pred)
print(y_test)

[-0.57211622  0.64741263]
[-0.66722767  0.88200808]


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmsc =np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(mae)
print(mse)
print(rmsc)

0.16485344804560453
0.03204060589877667
0.17899889915520897


In [ ]:
y_pred1 = y_pred.reshape(-1,1)  #convert the 1d data to 2d
y_test1 = y_test.reshape(-1,1)
y_pred2 = sc_y.inverse_transform(y_pred1)
y_test2 = sc_y.inverse_transform(y_test1)

print(y_pred1)
print(y_pred2)
print(y_test1)
print(y_test2)

p1= sc_X.transform([[5000]])
print(p1)
p2=sc_X.inverse_transform(p1)
print(p2)

[[-0.57211622]
 [ 0.64741263]]
[[-0.57211622]
 [ 0.64741263]]
[[-0.66722767]
 [ 0.88200808]]
[[-0.66722767]
 [ 0.88200808]]
[[5000.]]
[[5000.]]
